version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamongan-dev-website
    ports:
      - "8040:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - lamongan-dev_net

  db:
    image: mariadb:10.11
    container_name: lamongan-dev-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lamongan-dev_db
      MYSQL_USER: lamongan-dev
      MYSQL_PASSWORD: 200400
      MYSQL_ROOT_PASSWORD: 200400
    ports:
      - "3350:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamongan-dev_net

networks:
  lamongan-dev_net:

volumes:
  db_data:
